import { assetUrl } from './assets';
import { useState, useEffect } from 'react';
import { Play, Printer, Download, Volume2, VolumeX, Orbit, BookOpen, Check, WifiOff } from 'lucide-react';
import Hero, { Brand } from './Hero';
import { Introduction, Exploration, Journey, Comparison, Solutions, SectionTitle } from './Exploration';
import Presentation, { PrintPresentation } from './Presentation';
import Quiz from './Quiz';
import useAmbientSound from './useAmbientSound';
import { slides, conclusion, sources, type RegionId } from './data';
import imageCredits from './imageCredits.json';

export default function App() {
  const [selected,setSelected]=useState<RegionId>('space');const [presentation,setPresentation]=useState<number|null>(null);
  const [printNotes,setPrintNotes]=useState(false);const [offline,setOffline]=useState(!navigator.onLine);
  const [ready,setReady]=useState(false);const sound=useAmbientSound();
  useEffect(()=>{const online=()=>setOffline(!navigator.onLine);window.addEventListener('online',online);window.addEventListener('offline',online);if(import.meta.env.PROD&&'serviceWorker' in navigator)navigator.serviceWorker.register(assetUrl('sw.js'),{scope:import.meta.env.BASE_URL}).then(()=>navigator.serviceWorker.ready).then(()=>setReady(true)).catch(()=>{});return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',online);};},[]);
  function selectRegion(id:string){setSelected(id as RegionId);document.getElementById('regions')?.scrollIntoView({behavior:'smooth'});}
  function present(index=0){setPresentation(index);if(document.documentElement.requestFullscreen)void document.documentElement.requestFullscreen().catch(()=>{});}
  function downloadScript(){const script='BEYOND THE HORIZON: Exploring the Unknown\nGrade 10 English — speaking script\n\n'+slides.map((slide,index)=>`${String(index+1).padStart(2,'0')}. ${slide.title}\n${slide.notes}\n`).join('\n');const url=URL.createObjectURL(new Blob([script],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Beyond-the-Horizon-speaking-script.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <><a className="skip-link" href="#regions">Skip to exploration</a><div className="website" inert={presentation!==null}>
    <Hero onPresent={()=>present()} onRegion={selectRegion}/>
    <main><Introduction/><Exploration selected={selected} onSelect={setSelected} onPresent={present}/><Journey/><Comparison/><Solutions/>
      <section className="page-width section classroom-section" id="classroom"><SectionTitle number="05" label="THE CLASSROOM" title="Bring the journey to life." description="Present the story, discuss the choices, and put your knowledge to the test."/>
        <div className="classroom-layout"><div className="presentation-kit"><div className="kit-heading"><span className="kit-icon"><Play size={22} fill="currentColor"/></span><span>YOUR PRESENTATION, READY TO GO</span></div><h3>15 slides.<br/>One big conversation.</h3><p>From “What is exploration?” to a balanced conclusion. Short, clear slides with a natural speaking script for every step.</p><button className="button button-primary" onClick={()=>present()}><Play size={16} fill="currentColor"/> Launch presentation</button><div className="presentation-roadmap">{[{number:'01—03',label:'The question & our purpose'},{number:'04—08',label:'The five frontiers'},{number:'09—12',label:'Risks, solutions & our impact'},{number:'13—15',label:'Our opinion & your questions'}].map(x=><div key={x.number}><span>{x.number}</span><p>{x.label}</p></div>)}</div><div className="kit-tools"><a href={assetUrl("Beyond-the-Horizon.pdf")} download><Download size={16}/> Download slide PDF</a><button onClick={downloadScript}><Download size={16}/> Download speaking script</button><button onClick={()=>window.print()}><Printer size={16}/> Print / save as PDF</button><label><input type="checkbox" checked={printNotes} onChange={e=>setPrintNotes(e.target.checked)}/> Include speaker notes when printing</label></div><p className="kit-tip"><BookOpen size={15}/>Use ← → for slides and N for notes. For a PDF, choose “Save as PDF” in your browser’s print window.</p></div><Quiz/></div>
      </section>
      <section className="conclusion-section"><div className="page-width"><div className="eyebrow">THE HORIZON IS ONLY THE BEGINNING</div><h2>Keep the curiosity.<br/><em>Carry the responsibility.</em></h2><blockquote>{conclusion}</blockquote><div className="conclusion-values"><span><Check size={16}/> A clear purpose</span><span><Check size={16}/> A careful plan</span><span><Check size={16}/> Respect for our planet</span></div></div></section>
      <section className="page-width sources-section section" id="sources"><div className="sources-heading"><div><div className="eyebrow">CURIOSITY, BACKED BY SCIENCE</div><h2>Our sources.</h2></div><span>CHECKED 8 OCTOBER 2026</span></div><p>We used scientific organizations and historical collections for the facts. Our recommendations and final opinion are classroom arguments. The comparison ratings are discussion judgments, not measured data.</p><details className="sources-details"><summary><BookOpen size={18}/> Research & references <span>{sources.length} sources</span></summary><div className="source-list">{sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer"><span>{s.organization}</span><h3>{s.title}</h3><p>{s.supports}</p></a>)}</div></details><details className="sources-details"><summary><Orbit size={18}/> Photography & map credits <span>6 photographs</span></summary><div className="image-credit-list">{imageCredits.map(c=><div key={c.file}><h3>{c.title}</h3><p>{c.credit} · Resized and cropped for this project.</p><a href={c.source} target="_blank" rel="noreferrer">Original source</a><a href={c.licenseUrl} target="_blank" rel="noreferrer">{c.license}</a></div>)}<div><h3>World map</h3><p>Natural Earth public-domain land geometry, distributed in world-atlas 2.0.2. The map is a location guide, not a route-planning tool.</p><a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a></div></div></details></section>
    </main>
    <footer className="site-footer page-width"><Brand/><p>A GRADE 10 ENGLISH EXPLORATION PROJECT</p><div><span className="offline-status">{offline?<><WifiOff size={13}/>Offline · content stays available</>:ready?<><Check size={13}/>Ready for offline visits</>:<>Map, photos & fonts stored locally</>}</span><button onClick={()=>void sound.toggle()} aria-pressed={sound.enabled} title="Soft ambient sound; off by default">{sound.enabled?<Volume2 size={16}/>:<VolumeX size={16}/>} {sound.error?'Sound unavailable':sound.enabled?'Ambient on':'Ambient off'}</button></div></footer>
  </div>
  {presentation!==null&&<Presentation initialSlide={presentation} onClose={()=>setPresentation(null)} onQuiz={()=>setTimeout(()=>document.getElementById('quiz')?.scrollIntoView({behavior:'smooth'}),0)}/>}
  <PrintPresentation includeNotes={printNotes}/></>;
}
