import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import Quiz from './Quiz';
import Presentation from './Presentation';
import { ProblemCard, Exploration, Comparison } from './Exploration';
import { quizQuestions, regions, slides } from './data';

describe('classroom interactions',()=>{
  it('reveals the correct solution and can close it',async()=>{const user=userEvent.setup();const problem=regions[1].problems[0];render(<ProblemCard problem={problem} index={0}/>);const trigger=screen.getByRole('button');expect(trigger.getAttribute('aria-expanded')).toBe('false');await user.click(trigger);expect(screen.getByText(problem.solution).closest('[hidden]')).toBeNull();await user.click(trigger);expect(trigger.getAttribute('aria-expanded')).toBe('false');});
  it('scores a mixed set of answers, prevents changes, and resets the quiz',async()=>{const user=userEvent.setup();render(<Quiz/>);await user.click(screen.getByRole('button',{name:'Take the classroom quiz'}));for(let i=0;i<quizQuestions.length;i++){const q=quizQuestions[i];const chosen=i===1?(q.answer+1)%4:q.answer;await user.click(screen.getByRole('button',{name:new RegExp(q.choices[chosen].replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}));expect(screen.getByRole('status').textContent).toContain(q.explanation);expect(screen.getByRole('button',{name:new RegExp(q.choices[q.answer].replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).hasAttribute('disabled')).toBe(true);await user.click(screen.getByRole('button',{name:i===4?'See final score':'Next question'}));}expect(screen.getByRole('heading',{name:'You scored 4 / 5'})).toBeTruthy();await user.click(screen.getByRole('button',{name:'Try again'}));expect(screen.getByText('0 correct so far')).toBeTruthy();expect(screen.getByRole('heading',{name:quizQuestions[0].question})).toBeTruthy();});
  it('navigates with arrows, opens notes, reaches boundaries, and exits',async()=>{const close=vi.fn();render(<Presentation initialSlide={0} onClose={close} onQuiz={vi.fn()}/>);expect((screen.getByRole('button',{name:'Previous slide'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'ArrowRight'});expect(await screen.findByRole('heading',{name:slides[1].title})).toBeTruthy();fireEvent.keyDown(document,{key:'n'});expect(screen.getByText(slides[1].notes)).toBeTruthy();fireEvent.keyDown(document,{key:'End'});expect(await screen.findByRole('heading',{name:'Thank you.',level:2})).toBeTruthy();expect((screen.getByRole('button',{name:'Next slide'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Home'});expect(screen.getByRole('progressbar').getAttribute('aria-valuenow')).toBe('1');fireEvent.keyDown(document,{key:'Escape'});expect(close).toHaveBeenCalledOnce();});
  it('supports keyboard activation of map regions',()=>{const select=vi.fn();render(<Exploration selected="space" onSelect={select} onPresent={vi.fn()}/>);fireEvent.keyDown(screen.getByRole('button',{name:'Explore Rainforests'}),{key:'Enter'});expect(select).toHaveBeenCalledWith('rainforest');});
  it('changes comparison columns and the selected regional insight',async()=>{const user=userEvent.setup();render(<Comparison/>);await user.click(screen.getByRole('button',{name:'Environment',exact:true}));expect(screen.getAllByRole('columnheader')).toHaveLength(2);await user.click(screen.getByRole('button',{name:'Space',exact:true}));expect(screen.getByText('Knowledge of other worlds')).toBeTruthy();});
});
