import { assetUrl, regionSrcSet } from './assets';
import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { X, ChevronLeft, ChevronRight, Maximize, Minimize, NotebookPen, Compass, Microscope, Users, Sparkles, ShieldCheck, Leaf, Radio, Package, Thermometer, Bot, Satellite, Orbit, Play } from 'lucide-react';
import { slides, regionById, slideArguments, conclusion, sources, technologies, type Slide } from './data';
import { regionIcons, SourceLinks } from './Exploration';

export function SlideContent({ slide, index }: { slide: Slide; index: number }) {
  if (slide.kind==='title'||slide.kind==='thanks') return <div className={`slide-cover ${slide.kind}`}><div className="slide-cover-photo" /><div className="slide-cover-content"><span className="eyebrow"><Orbit size={20} /> GRADE 10 ENGLISH / EXPLORATION</span><h2>{slide.kind==='title'?<>BEYOND THE<br /><span>HORIZON.</span></>:<>Thank<br /><em>you.</em></>}</h2><p className="slide-cover-subtitle">{slide.subtitle}</p>{slide.kind==='title'?<p className="slide-cover-text">Five frontiers. Extraordinary discoveries.<br />One shared future.</p>:<div className="slide-questions"><p>Which frontier would you choose?</p><p>How would you explore it responsibly?</p></div>}<div className="slide-cover-icons">{Object.entries(regionIcons).map(([id,Icon])=><span key={id}><Icon size={21} />{regionById[id as keyof typeof regionById].name}</span>)}</div></div></div>;
  return <div className={`slide-content slide-kind-${slide.kind}`}>
    <div className="slide-heading"><span className="eyebrow">BEYOND THE HORIZON / {String(index+1).padStart(2,'0')}</span><h2>{slide.title}</h2><p>{slide.subtitle}</p></div>
    <div className="slide-body">
      {slide.kind==='concept'&&<><p className="slide-lead">Investigating places and ideas<br />to learn something new.</p><div className="slide-card-grid three"><SlideCard Icon={Compass} title="Ask a question" text="What do we want to understand?" /><SlideCard Icon={Microscope} title="Find evidence" text="Observe, measure, and record." /><SlideCard Icon={Users} title="Share knowledge" text="Help others learn from the results." /></div><p className="slide-bottom-note">Tourism is mainly for enjoyment. Scientific exploration has a research purpose.<br />A place can be new to a researcher and already familiar to local people.</p></>}
      {slide.kind==='motives'&&<><div className="slide-card-grid three"><SlideCard Icon={Sparkles} title="Curiosity" text="Understand Earth, other worlds, and the life around us." /><SlideCard Icon={Bot} title="Better solutions" text="Develop technology and answer useful questions." /><SlideCard Icon={Leaf} title="A shared future" text="Use discoveries to understand and protect nature." /></div><div className="slide-focus"><span>OUR PRESENTATION FOCUS</span><p>Five environments · Benefits and risks · Problems and solutions</p></div></>}
      {slide.kind==='region'&&slide.region&&<RegionSlide slide={slide} />}
      {slide.kind==='compare'&&<><div className="slide-two-columns"><div className="slide-positive"><span>ARGUMENTS FOR</span><h3>What we gain</h3><ul><li>New discoveries and useful knowledge</li><li>Better tools and technology</li><li>A clearer picture of our changing planet</li></ul></div><div className="slide-negative"><span>ARGUMENTS AGAINST</span><h3>What we risk</h3><ul><li>Large costs and competing needs</li><li>Danger to explorers and support teams</li><li>Damage to habitats and communities</li></ul></div></div><p className="slide-bottom-note">A useful discovery still needs to justify its cost, danger, and impact.</p></>}
      {slide.kind==='problems'&&<div className="slide-card-grid four"><SlideCard Icon={Thermometer} title="Extreme conditions" text="Cold, pressure, radiation, or altitude → protection and tested equipment." /><SlideCard Icon={Package} title="Limited supplies" text="Food, water, power, or spare parts → careful planning and backups." /><SlideCard Icon={Radio} title="Communication" text="Distance and weak signals → reliable systems and clear procedures." /><SlideCard Icon={ShieldCheck} title="Help far away" text="Delayed rescue → training, emergency plans, and safe stopping rules." /></div>}
      {slide.kind==='technology'&&<div className="slide-card-grid four">{technologies.map((t,i)=><SlideCard key={t.name} Icon={[Bot,Satellite,ShieldCheck,Users][i]} title={t.name} text={['Rovers and ROVs keep people away from the most dangerous conditions.','Satellites, sonar, and cameras help teams plan and observe.','Protective equipment, backups, and forecasts reduce risks.','Scientists, local guides, and communities learn together.'][i]} />)}</div>}
      {slide.kind==='environment'&&<><p className="slide-lead">Study a place.<br /><em>Help protect its future.</em></p><div className="slide-card-grid three"><SlideCard Icon={Microscope} title="Observe first" text="Use cameras and remote tools where possible. Limit sampling." /><SlideCard Icon={Leaf} title="Reduce the impact" text="Remove waste, prevent spills, and avoid disturbing wildlife." /><SlideCard Icon={Users} title="Respect people" text="Follow local rules, seek agreement, and share benefits." /></div><p className="slide-bottom-note">Research can guide conservation. Careless exploration can damage what it studies.</p></>}
      {slide.kind==='debate'&&<><div className="slide-two-columns"><div className="slide-positive"><span>YES, BECAUSE…</span><h3>Knowledge helps us.</h3><p>Discoveries can improve technology, explain our world, and support conservation.</p></div><div className="slide-negative"><span>BUT WE MUST ASK…</span><h3>Is this mission worth it?</h3><p>Could the money meet urgent needs? Can we manage the danger and environmental cost?</p></div></div><div className="slide-position"><ShieldCheck size={28} /><p>Our answer: <strong>yes—with a clear purpose, careful planning, and respect.</strong></p></div></>}
      {slide.kind==='conclusion'&&<div className="slide-conclusion"><span className="quote-mark">“</span><blockquote>{conclusion}</blockquote><div><span><Sparkles size={21} /> Stay curious</span><span><ShieldCheck size={21} /> Stay safe</span><span><Leaf size={21} /> Show respect</span></div></div>}
    </div>
    <div className="slide-citations"><SourceLinks ids={slide.sources} /></div>
  </div>;
}
function SlideCard({ Icon, title, text }: { Icon: typeof Compass; title: string; text: string }) {return <div className="slide-card"><Icon size={31} /><h3>{title}</h3><p>{text}</p></div>;}
function RegionSlide({ slide }: { slide: Slide }) {
  const r=regionById[slide.region!]; const Icon=regionIcons[r.id];const args=slideArguments[r.id];
  return <div className={`slide-region-layout region-${r.id}`} style={{'--region-color':r.color} as React.CSSProperties}><figure><img src={assetUrl(`assets/${r.id}.webp`)} srcSet={regionSrcSet(r.id)} sizes="(max-width: 560px) 90vw, 32vw" decoding="async" alt={r.imageAlt} width="1000" height="650" /><div className="slide-region-photo-label"><Icon size={28} /><span>{r.location}</span></div><figcaption>{r.caption}</figcaption></figure><div className="slide-region-arguments"><div className="slide-two-columns"><div className="slide-positive"><span>ADVANTAGES</span><ul>{args.benefits.map(text=><li key={text}>{text}</li>)}</ul></div><div className="slide-negative"><span>DISADVANTAGES</span><ul>{args.risks.map(text=><li key={text}>{text}</li>)}</ul></div></div><div className="slide-region-solution"><ShieldCheck size={21} /><div><span>A POSSIBLE SOLUTION</span><p>{r.problems[0].solution}</p></div></div></div></div>;
}
export default function Presentation({ initialSlide, onClose, onQuiz }: { initialSlide: number; onClose: () => void; onQuiz: () => void }) {
  const [index,setIndex]=useState(initialSlide); const [notes,setNotes]=useState(false);
  const [fullscreen,setFullscreen]=useState(!!document.fullscreenElement); const [direction,setDirection]=useState(1);
  const container=useRef<HTMLDivElement>(null); const closeButton=useRef<HTMLButtonElement>(null);
  const reduced=useReducedMotion(); const slide=slides[index];
  function navigate(next:number){const n=Math.max(0,Math.min(slides.length-1,next));setDirection(n>=index?1:-1);setIndex(n);}
  function close(){if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});onClose();}
  function toggleFullScreen(){if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});else void document.documentElement.requestFullscreen?.().catch(()=>{});}
  useEffect(()=>{const previouslyFocused=document.activeElement as HTMLElement|null;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';closeButton.current?.focus();return()=>{document.body.style.overflow=previousOverflow;previouslyFocused?.focus();};},[]);
  useEffect(()=>{const change=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change);},[]);
  useEffect(()=>{
    function keyboard(e:KeyboardEvent){const target=e.target as HTMLElement;
      if(e.key==='Tab'){const focusable=Array.from(container.current?.querySelectorAll<HTMLElement>('button:not([disabled]), select, a[href]')||[]).filter(el=>el.offsetParent!==null);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}
      if(e.key==='Escape'){e.preventDefault();close();return;}
      if(target.tagName==='SELECT'||target.tagName==='INPUT')return;
      if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();navigate(index+1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();navigate(index-1);}if(e.key==='Home'){e.preventDefault();navigate(0);}if(e.key==='End'){e.preventDefault();navigate(slides.length-1);}if(e.key.toLowerCase()==='n'){e.preventDefault();setNotes(prev=>!prev);}if(e.key==='Escape'){e.preventDefault();close();}
    }
    document.addEventListener('keydown',keyboard);return()=>document.removeEventListener('keydown',keyboard);
  },[index]);
  return <div className="presentation" role="dialog" aria-modal="true" aria-label="Beyond the Horizon presentation" ref={container}>
    <div className="presentation-topbar"><span><Orbit size={21}/> BEYOND THE HORIZON</span><div><button className={notes?'active':''} aria-pressed={notes} onClick={()=>setNotes(!notes)} title="Toggle speaker notes (N)"><NotebookPen size={18}/><span>Speaker notes</span></button><button onClick={toggleFullScreen} aria-label={fullscreen?'Exit full screen':'Enter full screen'}>{fullscreen?<Minimize size={18}/>:<Maximize size={18}/>}</button><button onClick={close} ref={closeButton} aria-label="Close presentation"><X size={20}/></button></div></div>
    <div className={`presentation-workspace ${notes?'has-notes':''}`}><div className="presentation-stage"><AnimatePresence mode="wait" initial={false} custom={direction}><motion.div key={index} className="slide-transition" custom={direction} initial={reduced?false:{opacity:0,x:direction*35}} animate={{opacity:1,x:0}} exit={reduced?undefined:{opacity:0,x:direction*-25}} transition={{duration:.22}}><SlideContent slide={slide} index={index}/></motion.div></AnimatePresence><span className="slide-accessible-status" aria-live="polite">Slide {index+1} of {slides.length}: {slide.title}</span></div>{notes&&<aside className="speaker-notes"><div><NotebookPen size={19}/><h3>Speaker notes</h3><button onClick={()=>setNotes(false)} aria-label="Hide speaker notes"><X size={16}/></button></div><span>SLIDE {index+1} / {slides.length}</span><h4>{slide.title}</h4><p>{slide.notes}</p><small>Read naturally. Pause between ideas.<br/>Press N to hide these notes before projecting.</small></aside>}</div>
    <div className="presentation-bottom"><div className="presentation-progress" role="progressbar" aria-label="Presentation progress" aria-valuenow={index+1} aria-valuemin={1} aria-valuemax={slides.length}><span style={{width:`${(index+1)/slides.length*100}%`}}/></div><div className="presentation-controls"><div className="slide-selector"><label htmlFor="jump-slide">SLIDE</label><select id="jump-slide" value={index} onChange={e=>navigate(Number(e.target.value))}>{slides.map((s,i)=><option key={s.title} value={i}>{String(i+1).padStart(2,'0')} / {slides.length} — {s.title}</option>)}</select></div><span className="keyboard-hint">← → to navigate <i>·</i> N for notes <i>·</i> Esc to exit</span><div className="slide-nav">{index===slides.length-1&&<button className="quiz-from-slides" onClick={()=>{close();onQuiz();}}><Play size={15}/>Quiz</button>}<button disabled={index===0} onClick={()=>navigate(index-1)} aria-label="Previous slide"><ChevronLeft size={21}/></button><span>{String(index+1).padStart(2,'0')}<i> / {slides.length}</i></span><button disabled={index===slides.length-1} onClick={()=>navigate(index+1)} aria-label="Next slide"><ChevronRight size={21}/></button></div></div></div>
  </div>;
}
export function PrintPresentation({ includeNotes }: { includeNotes: boolean }) {
  return <div className={`print-presentation ${includeNotes?'with-notes':''}`}>{slides.map((slide,index)=><article key={slide.title} className="print-slide"><SlideContent slide={slide} index={index}/><div className="print-slide-number">Beyond the Horizon · Slide {index+1} / {slides.length}</div>{includeNotes&&<div className="print-speaker-notes"><h3>Speaking script</h3><p>{slide.notes}</p></div>}</article>)}<article className="print-references"><h2>Research & references</h2><p>Beyond the Horizon · Grade 10 English · Sources checked 8 October 2026</p><ol>{sources.map(s=><li key={s.id}><strong>{s.organization}: {s.title}</strong><p>{s.supports}</p><a href={s.url}>{s.url}</a></li>)}</ol><p>Photo credits and licenses are included in the project’s IMAGE_CREDITS.md and the website’s Sources section.</p></article></div>;
}
