import { useState, useRef } from 'react';
import { Check, X, RotateCcw, Trophy, Brain, Play } from 'lucide-react';
import { quizQuestions, quizScore } from './data';

export default function Quiz() {
  const [started,setStarted]=useState(false); const [current,setCurrent]=useState(0);
  const [answers,setAnswers]=useState<(number|null)[]>(Array(quizQuestions.length).fill(null));
  const [finished,setFinished]=useState(false); const headingRef=useRef<HTMLHeadingElement>(null);
  const q=quizQuestions[current]; const answer=answers[current]; const score=quizScore(answers);
  function reset(){setAnswers(Array(quizQuestions.length).fill(null));setCurrent(0);setFinished(false);setStarted(true);}
  function choose(i:number){if(answer!==null)return;setAnswers(prev=>prev.map((a,j)=>j===current?i:a));}
  function next(){if(current===quizQuestions.length-1)setFinished(true);else setCurrent(current+1);setTimeout(()=>headingRef.current?.focus(),0);}
  return <div className="quiz-panel" id="quiz">
    {!started ? <div className="quiz-start"><span className="quiz-icon"><Brain size={34} /></span><div className="eyebrow">THE CURIOSITY CHECK</div><h3>How far did your<br />knowledge travel?</h3><p>Five questions. Five frontiers.<br />A little curiosity goes a long way.</p><button className="button button-primary" onClick={()=>{setStarted(true);setTimeout(()=>headingRef.current?.focus(),0);}}><Play size={15} fill="currentColor" /> Take the classroom quiz</button><span className="quiz-start-meta">INSTANT FEEDBACK · NO TIMER</span></div> : finished ? <div className="quiz-results" aria-live="polite"><Trophy size={43} /><div className="eyebrow">EXPEDITION COMPLETE</div><h3 ref={headingRef} tabIndex={-1}>You scored <span>{score} / 5</span></h3><p>{score===5 ? 'Excellent exploring! You understand both the discoveries and the responsibilities.' : score>=3 ? 'Good exploring! Review the explanations, then give it another go.' : 'Every discovery starts with learning. Review your answers and try again.'}</p><div className="quiz-review">{quizQuestions.map((question,i)=><details key={i}><summary><span className={answers[i]===question.answer?'correct-icon':'wrong-icon'}>{answers[i]===question.answer ? <Check size={16} />:<X size={16} />}</span>Question {i+1}<span>{answers[i]===question.answer?'Correct':'Review'}</span></summary><p>{question.question}</p><strong>{question.choices[question.answer]}</strong><p>{question.explanation}</p></details>)}</div><button className="button button-glass" onClick={reset}><RotateCcw size={16} /> Try again</button></div> : <div className="quiz-question"><div className="quiz-question-top"><span>QUESTION {current+1} OF {quizQuestions.length}</span><span>{score} correct so far</span></div><div className="quiz-progress">{quizQuestions.map((_,i)=><i key={i} className={i<=current?'active':''} />)}</div><h3 ref={headingRef} tabIndex={-1}>{q.question}</h3><div className="quiz-choices">{q.choices.map((choice,i)=><button key={choice} disabled={answer!==null} className={`${answer!==null&&i===q.answer?'correct':''} ${answer===i&&i!==q.answer?'incorrect':''}`} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{choice}{answer!==null&&i===q.answer&&<Check size={19} />}{answer===i&&i!==q.answer&&<X size={19} />}</button>)}</div>{answer!==null&&<div className={`quiz-feedback ${answer===q.answer?'correct':'incorrect'}`} role="status"><strong>{answer===q.answer?'That’s right!':'A good question to learn from.'}</strong><p>{q.explanation}</p><button className="button button-primary" onClick={next}>{current===quizQuestions.length-1?'See final score':'Next question'}</button></div>}</div>}
  </div>;
}
